import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "bun:test";

test("OpenTUI app shell renders live view fields and Phase 66 command surfaces", async () => {
  const source = await readFile(new URL("../src/opentui/App.tsx", import.meta.url), "utf8");

  assert.doesNotMatch(source, /OpenTUI sidecar proof\. Full transcript port begins after migration contract\./);
  assert.match(source, /view\.transcriptBlocks/);
  assert.doesNotMatch(source, /expandedTraceBlocks/);
  assert.match(source, /renderTraceProgressRows/);
  assert.match(source, /parseTraceProgressEvent/);
  assert.match(source, /kind\\s\+\(\\w\+\)/);
  assert.match(source, /traceProgressPaletteKey/);
  assert.match(source, /traceDetailScrollOffset/);
  assert.match(source, /handleTraceProgressRowClick/);
  assert.match(source, /setTraceProgressPaletteKey\(\(current\) => current === row\.toggleKey \? null : row\.toggleKey\)/);
  assert.match(source, /renderTraceDetailPaletteRows/);
  assert.match(source, /traceDetailContentLines/);
  assert.match(source, /zIndex=\{95\}/);
  assert.match(source, /onMouseScroll=\{\(event\) => handleTraceDetailPaletteMouseScroll\(event\)\}/);
  assert.match(source, /wheel\/PageUp\/PageDown · Esc close/);
  assert.match(source, /row\.text\.replace/);
  assert.match(source, /limitTraceProgressRows/);
  assert.match(source, /markActiveTraceProgressRow/);
  assert.match(source, /" \[-\]"/);
  assert.match(source, /const compactPrefix = compactIcon \? `\$\{compactIcon\} ` : ""/);
  assert.match(source, /if \(block\.kind === "tool"\) {\n\s+return "";/);
  assert.match(source, /progressRowBudget/);
  assert.match(source, /const transcriptBlocks = view\.transcriptBlocks/);
  assert.doesNotMatch(source, /view\.composerHint/);
  assert.match(source, /traceExpanded/);
  assert.match(source, /createOpenTuiTranscriptState/);
  assert.match(source, /visibleLineWindow/);
  assert.doesNotMatch(source, /submitted shell intent:/);
  assert.doesNotMatch(source, /history placeholder - Phase 66/);
  assert.doesNotMatch(source, /model picker placeholder - Phase 66/);
  assert.match(source, /No matches/);
  assert.match(source, /Select skill/);
  assert.match(source, /skill:/);
  assert.match(source, /\[X\] clear/);
  assert.match(source, /handleAttachmentClearClick/);
  assert.match(source, /row\.key === "composer-attachment" && composer\.attachment\?\.supported/);
  assert.match(source, /formatAttachmentListLabel/);
  assert.match(source, /\[Image #\$\{String\(index\)\}\]/);
  assert.match(source, /attachmentLabel: composer\.attachment\?\.supported \? composer\.attachment\.label : null/);
  assert.match(source, /extractClipboardImageToTempFile/);
  assert.match(source, /applyAttachmentMutationCommand/);
  assert.match(source, /pendingImageAttachments/);
  assert.match(source, /No history matches/);
  assert.match(source, /move-selection/);
  assert.match(source, /accept-selection/);
  assert.match(source, /move-cursor/);
  assert.match(source, /move-cursor-to/);
  assert.match(source, /renderComposerLine/);
  assert.match(source, /renderComposerPromptRows/);
  assert.match(source, /COMPOSER_VISIBLE_PROMPT_ROWS = 4/);
  assert.match(source, /printableValue/);
  assert.match(source, /keyboardSource/);
  assert.match(source, /subscribe/);
  assert.match(source, /selectedValue\.trim\(\) === composer\.text\.trim\(\)/);
  assert.match(source, /paletteRows\.length === 0/);
  assert.doesNotMatch(source, /key\.name === "q" \|\|/);
  assert.doesNotMatch(source, /setOutputBlocks/);
  assert.doesNotMatch(source, /createLocalOutputBlock/);
  assert.doesNotMatch(source, /appendOutput\(result\.output\)/);
  assert.match(source, /recordCommandOutputEvent/);
  assert.match(source, /kind: "command"/);
  assert.match(source, /intent\.input\.trim\(\) === "\/quit"/);
  assert.match(source, /ALT_V_UNSUPPORTED_MESSAGE/);
  assert.match(source, /CTRL_V_UNSUPPORTED_MESSAGE/);
  assert.match(source, /key\.ctrl && key\.name === "v"/);
  assert.match(source, /readClipboardText/);
  assert.match(source, /Ctrl\+V text/);
  assert.match(source, /COMPOSER_CURSOR/);
  assert.match(source, /COPIED_RESULTS_NOTICE/);
  assert.match(source, /copyTextToClipboardOsc52/);
  assert.doesNotMatch(source, /key\.ctrl && key\.name === "c"/);
  assert.match(source, /copyLatestResultBlock/);
  assert.match(source, /key\.ctrl && key\.name === "q"/);
  assert.match(source, /key\.meta \|\| key\.option/);
  assert.match(source, /onMouseScroll/);
  assert.match(source, /onMouseUp/);
  assert.match(source, /handleTranscriptMouseScroll/);
  assert.match(source, /event\.type === "scroll"/);
  assert.match(source, /MOUSE_SCROLL_LINES = 1/);
  assert.match(source, /transcriptLineColor/);
  assert.match(source, /selectable/);
  assert.match(source, /selectionBg/);
  assert.match(source, /PgUp\/PgDn scroll/);
  assert.match(source, /Ctrl\+Y copy/);
  assert.match(source, /visiblePaletteWindow/);
  assert.match(source, /createPaletteDisplayRows/);
  assert.match(source, /PALETTE_VISIBLE_ROWS = 5/);
  assert.match(source, /PALETTE_CHROME_ROWS = 5/);
  assert.match(source, /position="absolute"/);
  assert.match(source, /zIndex=\{100\}/);
  assert.match(source, /backgroundColor="#000000"/);
  assert.match(source, /overflow="hidden"/);
  assert.match(source, /shouldFill/);
  assert.match(source, /renderPalettePanelRows/);
  assert.match(source, /palettePanelRows\.map/);
  assert.match(source, /paletteTitleForOverlay/);
  assert.match(source, /\$ Skills/);
  assert.match(source, /History/);
  assert.match(source, /paletteFooterLine/);
  assert.match(source, /paletteOverlayHeight = PALETTE_VISIBLE_ROWS \+ PALETTE_CHROME_ROWS/);
  assert.match(source, /terminalHeight - composerReservedRows - STATUSLINE_RESERVED_ROWS - paletteOverlayHeight - 1/);
  assert.match(source, /palette-\$\{String\(index\)\}-\$\{row\.selected \? "selected" : "row"\}-\$\{row\.value\}/);
  assert.match(source, /transcriptPositionLabel/);
  assert.match(source, /view\.cockpit\.approval\.pendingTool/);
  assert.match(source, /Approval required/);
  assert.match(source, /zIndex=\{90\}/);
  assert.match(source, /WARNING_VISIBLE_ROWS = 3/);
  assert.match(source, /cockpitWarningOverflow/);
  assert.match(source, /cockpitExpanded/);
  assert.match(source, /key\.ctrl && key\.name === "p"/);
  assert.match(source, /configExpanded/);
  assert.match(source, /key\.ctrl && key\.name === "g"/);
  assert.match(source, /renderConfigPanelRows/);
  assert.match(source, /renderLogoRows/);
  assert.match(source, /view\.logo\.frames/);
  assert.match(source, /Ctrl\+G config/);
  assert.match(source, /zIndex=\{94\}/);
  assert.match(source, /configSelectedIndex/);
  assert.match(source, /moveConfigSelection/);
  assert.match(source, /applyConfigSelection/);
  assert.match(source, /\/config logo \$\{next\}/);
  assert.match(source, /\/config lsp on/);
  assert.match(source, /\/config lsp-index on/);
  assert.match(source, /handleConfigRowClick/);
  assert.match(source, /↑\/↓ select · Enter run · click select · Esc close/);
  assert.match(source, /showCockpitPanel = cockpitExpanded/);
  assert.doesNotMatch(source, /warning lane/);
  assert.doesNotMatch(source, /action ladder intent/);
  assert.match(source, /renderCockpitPanelRows/);
  assert.match(source, /╭\$\{title\}/);
  assert.match(source, /Turn/);
  assert.match(source, /Progress/);
  assert.doesNotMatch(source, /pilot override/);
  assert.match(source, /view\.cockpit\.overrideHints/);
  assert.match(source, /cockpitMemoryRows/);
  assert.match(source, /view\.cockpit\.memory\.active/);
  assert.match(source, /view\.cockpit\.memory\.retrieved/);
  assert.match(source, /WIDE_COCKPIT_MIN_COLUMNS/);
  assert.match(source, /wideCockpitLayout/);
  assert.match(source, /cockpitRowBudget/);
  assert.match(source, /composerReservedRows/);
  assert.match(source, /position="absolute"/);
  assert.match(source, /zIndex=\{80\}/);
  assert.match(source, /terminalHeight - composerReservedRows/);
  assert.match(source, /composerPanelHeight/);
  assert.match(source, /row\.canToggle/);
  assert.match(source, /#8bd5ff/);
  assert.match(source, /#f9e2af/);
  assert.match(source, /executeProviderRequest/);
  assert.match(source, /submitProviderPrompt/);
  assert.match(source, /autoInvokeAfterSkill/);
  assert.match(source, /result && !autoInvokeAfterSkill/);
  assert.match(source, /buildActiveSkillExecutionPrompt/);
  assert.match(source, /formatActiveSkillTranscriptPrompt/);
  assert.match(source, /transcriptPrompt/);
  assert.match(source, /recordConversationTurn/);
  assert.match(source, /createOpenTuiRuntimeView\(session\)/);
  assert.doesNotMatch(source, /appendAgentOutput/);
  assert.match(source, /chatDividerLine/);
  assert.match(source, /spinnerTick/);
  assert.match(source, /view\.status === "running"/);
  assert.match(source, /IDLE_REFRESH_INTERVAL_MS = 1000/);
  assert.match(source, /RUNNING_REFRESH_INTERVAL_MS = 80/);
  assert.match(source, /intervalMs = view\.status === "running" \? RUNNING_REFRESH_INTERVAL_MS : IDLE_REFRESH_INTERVAL_MS/);
  assert.match(source, /setSpinnerTick\(\(current\) => current \+ 1\);\n\s+scheduleRuntimeViewRefresh\(0\);/);
  assert.match(source, /subscribeRuntimeSession/);
  assert.match(source, /scheduleRuntimeViewRefresh\(16\)/);
  assert.match(source, /scheduleRuntimeViewRefresh\(0\)/);
  assert.match(source, /refreshTimerRef/);
  assert.match(source, /formatProgressChrome\(spinnerTick/);
  assert.match(source, /formatOpenTuiStatuslineProgress/);
  assert.match(source, /tokensTotal <= 0/);
  assert.match(source, /replace\(" · running · ", ` · \$\{view\.status\} · `\)/);
  assert.match(source, /formatTraceProgressMetricBadge/);
  assert.match(source, /readTraceProgressMetric\(detail, "turn_in"\)/);
  assert.match(source, /readTraceProgressMetric\(detail, "turn_out"\)/);
  assert.match(source, /` · \$\{metrics\}`/);
  assert.match(source, /progressPrefix = options\.progress/);
  assert.match(source, /Model:/);
  assert.match(source, /Mem: \$\{memLabel\}/);
  assert.match(source, /formatMemoryBytes\(options\.statusline\.memoryUsedBytes\)/);
  assert.match(source, /formatMemoryBytes\(options\.statusline\.memoryTotalBytes\)/);
  assert.match(source, /Git: \$\{gitLabel\}/);
  assert.match(source, /Context: \$\{contextBar\} \$\{String\(options\.statusline\.contextPercent\)\}%/);
  assert.match(source, /↓ In: \$\{formatCompactNumber\(options\.statusline\.lastInputTokens\)\}/);
  assert.match(source, /↑ Out: \$\{formatCompactNumber\(options\.statusline\.lastOutputTokens\)\}/);
  assert.match(source, /formatContextUsageBar/);
  assert.match(source, /"="\.repeat\(filled\)/);
  assert.match(source, /"-"\.repeat\(barWidth - filled\)/);
  assert.doesNotMatch(source, /Cost: \$0\.00/);
  assert.doesNotMatch(source, /\.\.\/runtime\/tools/);
});

test("OpenTUI entry shuts down hydrated MCP clients on exit", async () => {
  const source = await readFile(new URL("../src/opentui/entry.tsx", import.meta.url), "utf8");

  assert.match(source, /shutdownMcpRegistry/);
  assert.match(source, /shutdownMcpRegistry\(session\.mcpRegistry\)/);
  assert.match(source, /keyboardSource\.dispose\(\)/);
  assert.match(source, /renderer\.destroy\(\)/);
});

test("OpenTUI transcript scroll shortcuts preserve overlay selection ownership", async () => {
  const source = await readFile(new URL("../src/opentui/App.tsx", import.meta.url), "utf8");
  const upBranch = source.slice(source.indexOf('if (key.name === "up")'), source.indexOf('if (key.name === "down")'));
  const downBranch = source.slice(source.indexOf('if (key.name === "down")'), source.indexOf('if (key.name === "left")'));

  assert.ok(upBranch.indexOf('composer.overlayMode !== "none"') < upBranch.indexOf("key.ctrl"));
  assert.ok(downBranch.indexOf('composer.overlayMode !== "none"') < downBranch.indexOf("key.ctrl"));
  assert.match(upBranch, /move-selection/);
  assert.match(downBranch, /move-selection/);
  assert.match(upBranch, /scroll-lines/);
  assert.match(downBranch, /scroll-lines/);
});
