import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "bun:test";

test("OpenTUI app shell renders live view fields and Phase 66 command surfaces", async () => {
  const source = await readFile(new URL("../src/opentui/App.tsx", import.meta.url), "utf8");

  assert.doesNotMatch(source, /OpenTUI sidecar proof\. Full transcript port begins after migration contract\./);
  assert.match(source, /view\.transcriptBlocks/);
  assert.doesNotMatch(source, /view\.composerHint/);
  assert.match(source, /traceExpanded/);
  assert.match(source, /createOpenTuiTranscriptState/);
  assert.match(source, /visibleLineWindow/);
  assert.doesNotMatch(source, /submitted shell intent:/);
  assert.doesNotMatch(source, /history placeholder - Phase 66/);
  assert.doesNotMatch(source, /model picker placeholder - Phase 66/);
  assert.match(source, /No matches/);
  assert.match(source, /Select skill/);
  assert.match(source, /skill:/);
  assert.match(source, /clear attachment/);
  assert.match(source, /No history matches/);
  assert.match(source, /move-selection/);
  assert.match(source, /accept-selection/);
  assert.match(source, /move-cursor/);
  assert.match(source, /move-cursor-to/);
  assert.match(source, /renderComposerLine/);
  assert.match(source, /printableValue/);
  assert.match(source, /keyboardSource/);
  assert.match(source, /subscribe/);
  assert.match(source, /selectedValue\.trim\(\) === composer\.text\.trim\(\)/);
  assert.doesNotMatch(source, /key\.name === "q" \|\|/);
  assert.match(source, /outputBlocks/);
  assert.match(source, /createLocalOutputBlock/);
  assert.match(source, /result\.output/);
  assert.match(source, /intent\.input\.trim\(\) === "\/quit"/);
  assert.match(source, /ALT_V_UNSUPPORTED_MESSAGE/);
  assert.match(source, /COMPOSER_CURSOR/);
  assert.match(source, /COPIED_RESULTS_NOTICE/);
  assert.match(source, /copyTextToClipboardOsc52/);
  assert.match(source, /key\.ctrl && key\.name === "c"/);
  assert.match(source, /key\.ctrl && key\.name === "q"/);
  assert.match(source, /key\.meta \|\| key\.option/);
  assert.match(source, /onMouseScroll/);
  assert.match(source, /onMouseUp/);
  assert.match(source, /handleTranscriptMouseScroll/);
  assert.match(source, /event\.type === "scroll"/);
  assert.match(source, /selectable/);
  assert.match(source, /selectionBg/);
  assert.match(source, /PageUp\/PageDown Ctrl\+Up\/Ctrl\+Down wheel/);
  assert.match(source, /Ctrl\+C\/Ctrl\+Y copy/);
  assert.match(source, /visiblePaletteWindow/);
  assert.match(source, /PALETTE_VISIBLE_ROWS = 5/);
  assert.match(source, /position="absolute"/);
  assert.match(source, /zIndex=\{100\}/);
  assert.match(source, /backgroundColor="#000000"/);
  assert.match(source, /paletteOverlayHeight/);
  assert.match(source, /transcriptPositionLabel/);
  assert.match(source, /const composerLine = composer\.text\.length > 0 \? renderComposerLine\(composer, contentWidth\) : `> \$\{COMPOSER_CURSOR\}`/);
  assert.match(source, /row\.canToggle/);
  assert.match(source, /#8bd5ff/);
  assert.match(source, /#f9e2af/);
  assert.doesNotMatch(source, /\.\.\/provider/);
  assert.doesNotMatch(source, /\.\.\/runtime\/tools/);
});

test("OpenTUI transcript scroll shortcuts preserve overlay selection ownership", async () => {
  const source = await readFile(new URL("../src/opentui/App.tsx", import.meta.url), "utf8");
  const upBranch = source.slice(source.indexOf('if (key.name === "up")'), source.indexOf('if (key.name === "down")'));
  const downBranch = source.slice(source.indexOf('if (key.name === "down")'), source.indexOf('if (key.name === "left")'));

  assert.ok(upBranch.indexOf('composer.overlayMode !== "none"') < upBranch.indexOf("key.ctrl"));
  assert.ok(downBranch.indexOf('composer.overlayMode !== "none"') < downBranch.indexOf("key.ctrl"));
  assert.match(upBranch, /move-selection/);
  assert.match(downBranch, /move-selection/);
  assert.match(upBranch, /scroll-lines/);
  assert.match(downBranch, /scroll-lines/);
});
