export const COMMAND_CATALOG = [
  { name: "/help", usage: "/help", description: "show available runtime commands" },
  { name: "/keys", usage: "/keys", description: "show OpenTUI keyboard shortcuts and interaction modes" },
  { name: "/reload", usage: "/reload", description: "reload runtime state from repo config" },
  { name: "/quit", usage: "/quit", description: "exit interactive TTY session" },
  { name: "/continue", usage: "/continue", description: "continue active turn if clear" },
  { name: "/finish", usage: "/finish", description: "finalize current turn only when completion proof exists" },
  { name: "/login", usage: "/login [status]", description: "check or launch Codex login" },
  { name: "/codex", usage: "/codex [status|off]", description: "activate Codex provider preference" },
  { name: "/provider", usage: "/provider [status|name|transport ...] [--verbose]", description: "show or switch provider and transport mode" },
  { name: "/model", usage: "/model [status|list|name [effort]]", description: "show or set model for active provider" },
  { name: "/effort", usage: "/effort [status|low|medium|high|xhigh]", description: "show or set reasoning effort for active model" },
  { name: "/skill", usage: "/skill [name] [args...]", description: "list skills or resolve and route a skill by name" },
  { name: "/boomerang", usage: "/boomerang <task> | /boomerang status | /boomerang cancel", description: "run autonomous task then compact turn into handoff summary" },
  { name: "/goal", usage: "/goal [--tokens 50k] <objective> | /goal status | /goal pause | /goal resume | /goal clear | /goal statusbar on|off", description: "run persistent autonomous goal until complete, paused, cleared, or token-budget-limited" },
  { name: "/btw", usage: "/btw [--save] <question> | /btw:new [question] | /btw:tangent [--save] <question> | /btw:clear | /btw:inject [instructions] | /btw:summarize [instructions]", description: "run hidden side conversation and optionally inject it back" },
  { name: "/agents", usage: "/agents", description: "show Claude-style subagent types, running agents, and recent results" },
  { name: "/mouse", usage: "/mouse [status|mode <auto|scroll|select>]", description: "show or set transcript mouse interaction mode" },
  { name: "/status", usage: "/status [--verbose|--sentry [--send-test-event]]", description: "show runtime, repo, auth, style, and Sentry status" },
  { name: "/usage", usage: "/usage", description: "show current session usage statistics with provider/model token totals" },
  { name: "/todos", usage: "/todos [pending|in_progress|completed|all|clear]", description: "show or clear visual task checklist used by model planning" },
  { name: "/notify", usage: "/notify [on|off|status|threshold <ms>] | /notify-test", description: "control background terminal notifications for long turns" },
  { name: "/notify-test", usage: "/notify-test", description: "send a test terminal notification" },
  { name: "/emoji", usage: "/emoji [status|emoji] | /emoji-test", description: "show or set session emoji marker" },
  { name: "/emoji-test", usage: "/emoji-test", description: "print available session emoji markers" },
  { name: "/color", usage: "/color [status|index] | /color-next | /color-set <index>", description: "show or rotate session color marker" },
  { name: "/safegit", usage: "/safegit [status|patterns]", description: "inspect safe-git high-risk command guard" },
  { name: "/scip", usage: "/scip [status|symbols <path>|diagnostics <path>|check [path]]", description: "Pi SCIP compatibility aliases backed by local LSP" },
  { name: "/doctor", usage: "/doctor", description: "run compact runtime health checks and show concrete next actions" },
  { name: "/caveman-mode", usage: "/caveman-mode [on|off|status]", description: "toggle compressed caveman response style" },
  { name: "/deadpoolmode", usage: "/deadpoolmode [on|off|status]", description: "toggle Deadpool prose style overlay" },
  { name: "/statusline", usage: "/statusline [on|off|status|command <shell>|command clear]", description: "toggle or customize compact runtime statusline footer" },
  { name: "/approval", usage: "/approval [on|off|status|approve|allow-session|reject]", description: "control guarded-tool approval gate" },
  { name: "/ask", usage: "/ask [status|<option#|text>|answer <question#> <option#|1,2|text>|submit|cancel]", description: "answer pending ask_user_question prompt" },
  { name: "/cancel", usage: "/cancel", description: "request cancel for pending operation" },
  { name: "/steer", usage: "/steer <message>", description: "queue operator steer note for next tool/model step" },
  { name: "/compact", usage: "/compact [status]", description: "compact session context now or inspect compaction state" },
  { name: "/tools", usage: "/tools [--verbose]", description: "show repo-local tool policy and safety guards" },
  { name: "/why-blocked", usage: "/why-blocked", description: "explain latest blocked guarded shell command and safer recovery path" },
  { name: "/nexsight", usage: "/nexsight [stats|gather <root> [pattern] [query]|read <path> [mode]|index <path> [pattern]|search <query>|purge|doctor]", description: "manage local nexsight gather/execution/read/index/search context store" },
  { name: "/config", usage: "/config [status] | /config [set] <logo|lsp|lsp-index> <value>", description: "inspect or mutate persisted runtime configuration" },
  { name: "/lsp", usage: "/lsp [status|setup|health|warm|mode <on|off>|symbols <path>|diagnostics <path>|check [path]|nav <operation> [path] [line] [character]]", description: "inspect enabled local LSP code intelligence with bounded fallback" },
  { name: "/pwd", usage: "/pwd", description: "show current working directory" },
  { name: "/ls", usage: "/ls [path]", description: "list directory contents from session cwd" },
  { name: "/read", usage: "/read <path>", description: "read text file contents" },
  { name: "/find", usage: "/find <text> [path]", description: "search text in repo files" },
  { name: "/glob", usage: "/glob <pattern> [path]", description: "match repo files by glob pattern" },
  { name: "/rg", usage: "/rg <pattern> [path]", description: "search repo files with ripgrep" },
  { name: "/diff", usage: "/diff [path]", description: "show bounded git diff for repo or one path" },
  { name: "/hooks", usage: "/hooks", description: "inspect repo-local hook policy" },
  { name: "/extensions", usage: "/extensions", description: "inspect Pi-like runtime extension lifecycle and command shim" },
  { name: "/memory", usage: "/memory [status|--verbose|--maintenance|save <text>|checkpoint [reason]|session [focus]]", description: "inspect, maintain, or persist archivist memory/checkpoints" },
  { name: "/attach", usage: "/attach <image-path>", description: "attach local image for next prompt (http transports only)" },
  { name: "/detach", usage: "/detach", description: "clear queued image attachment" },
] as const;

export const PATH_COMPLETION_COMMANDS = new Set(["/ls", "/read", "/diff"]);
export const SECOND_ARG_PATH_COMMANDS = new Set(["/find", "/glob", "/rg"]);
export const PATH_SUBCOMMANDS = new Map<string, ReadonlySet<string>>([
  ["/lsp", new Set(["symbols", "diagnostics", "nav"])],
]);
